"""Build the level-shuffle notebook and its canonical level-name table."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def build():
    levels = json.loads(re.sub(r"(?m)^\s*//.*$", "",
        (ROOT / "locations/ui/levels.jsonc").read_text(encoding="utf-8")))
    names = [level["name"].removesuffix(" - Monkeys") for level in levels]
    items = [{"name": "Leads to", "type": "static", "codes": "entrance_arrow",
              "img": "images/maps/arrow.png"}]
    columns = []
    for first in range(0, len(names), 7):
        rows = []
        for index in range(first, min(first + 7, len(names))):
            number = index + 1
            source = f"entrance_source_{number}"
            destination = f"entrance_destination_{number}"
            items.append({"name": names[index],
                          "type": "static", "codes": source,
                          "img": f"images/maps/map-{number}.png"})
            stages = [{"name": "Unknown destination",
                       "img": "images/maps/nolevel.png", "codes": destination,
                       "inherit_codes": False}]
            stages += [{"name": name,
                        "img": f"images/maps/map-{target}.png",
                        "codes": f"{destination}_{target}", "inherit_codes": False}
                       for target, name in enumerate(names, 1)]
            items.append({"name": "Destination",
                          "type": "progressive", "allow_disabled": False,
                          "loop": True, "initial_stage_idx": 0, "stages": stages})
            rows.append([source, "entrance_arrow", destination])
        # Groups retain the grid's intrinsic width inside a horizontal array.
        # Each group contains seven source/destination rows.
        columns.append({"type": "group", "header": "",
                        "margin": "0,0,40,0" if first < 21 else "0,0,0,0", "content": {
                            "type": "itemgrid", "item_size": 60,
                            "item_margin": "6,5", "rows": rows}})
    layout = {"entrance_tracker": {"type": "array", "orientation": "horizontal",
                                    "content": columns}}
    for relative, data in [("items/entrances.jsonc", items), ("layouts/entrances.jsonc", layout)]:
        (ROOT / relative).write_text(
            "// Generated by tools/build_entrance_tracker.py. Do not edit manually.\n" +
            json.dumps(data, indent=2) + "\n", encoding="utf-8")
    (ROOT / "scripts/entrance_data.lua").write_text(
        "-- Generated by tools/build_entrance_tracker.py. Do not edit manually.\n" +
        "ENTRANCE_LEVEL_NAMES = {\n" +
        "".join("    " + json.dumps(name) + ",\n" for name in names) + "}\n",
        encoding="utf-8")


if __name__ == "__main__":
    build()
